// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByh2aNM0ilgnaERzHgHwsYvg8uqap_n2M',
    appId: '1:864648597432:android:48330c574537b4d779894d',
    messagingSenderId: '864648597432',
    projectId: 'news-app-30864',
    storageBucket: 'news-app-30864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyXAkObPtq9OrhedWbtX5wBHGA0ep5DE',
    appId: '1:864648597432:ios:64a838a5f20a602e79894d',
    messagingSenderId: '864648597432',
    projectId: 'news-app-30864',
    storageBucket: 'news-app-30864.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMyXAkObPtq9OrhedWbtX5wBHGA0ep5DE',
    appId: '1:864648597432:ios:64a838a5f20a602e79894d',
    messagingSenderId: '864648597432',
    projectId: 'news-app-30864',
    storageBucket: 'news-app-30864.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk3Bus0Tg-d5gQbsl35L03KWHwpzcZU2g',
    appId: '1:864648597432:web:8ca242f456d8343d79894d',
    messagingSenderId: '864648597432',
    projectId: 'news-app-30864',
    authDomain: 'news-app-30864.firebaseapp.com',
    storageBucket: 'news-app-30864.firebasestorage.app',
  );
}
